[workspace]
resolver = "2"
members = [
    "crates/runner",
    "crates/galexy-os",
    "crates/galexy-core",
    "crates/galexy-crypto",
    "crates/galexy-abi",
    "crates/galexy-galf",
    "crates/galfs-fsck",
    "crates/userspace/galexy-rt",
    "crates/userspace/hello",
    "crates/userspace/shell",
    "crates/userspace/util",
    "crates/gxc",
]
default-members = ["crates/runner"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
