[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
galexy-galf = { path = "../galexy-galf" }

[build-dependencies]
bootloader = "0.11"
tar = "0.4"
galexy-crypto = { path = "../galexy-crypto" }
gxc = { path = "../gxc" }
galexy-os = { path = "../galexy-os", artifact = "bin", target = "x86_64-unknown-none" }
hello = { path = "../userspace/hello", artifact = "bin", target = "x86_64-unknown-none" }
init = { path = "../userspace/init", artifact = "bin", target = "x86_64-unknown-none" }
shell = { path = "../userspace/shell", artifact = "bin", target = "x86_64-unknown-none" }
util = { path = "../userspace/util", artifact = "bin", target = "x86_64-unknown-none" }
