[package]
name = "util"
version = "0.1.0"
edition = "2021"
description = "Shell utilities as separate ring-3 programs."

[[bin]]
name = "echo"
path = "src/bin/echo.rs"

[[bin]]
name = "cat"
path = "src/bin/cat.rs"

[[bin]]
name = "nano"
path = "src/bin/nano.rs"

[[bin]]
name = "touch"
path = "src/bin/touch.rs"

[[bin]]
name = "mkdir"
path = "src/bin/mkdir.rs"

[[bin]]
name = "rm"
path = "src/bin/rm.rs"

[[bin]]
name = "ls"
path = "src/bin/ls.rs"

[[bin]]
name = "cp"
path = "src/bin/cp.rs"

[[bin]]
name = "mv"
path = "src/bin/mv.rs"

[[bin]]
name = "truncate"
path = "src/bin/truncate.rs"

[[bin]]
name = "stat"
path = "src/bin/stat.rs"

[[bin]]
name = "linger"
path = "src/bin/linger.rs"

[[bin]]
name = "head"
path = "src/bin/head.rs"

[[bin]]
name = "tail"
path = "src/bin/tail.rs"

[[bin]]
name = "wc"
path = "src/bin/wc.rs"

[[bin]]
name = "grep"
path = "src/bin/grep.rs"

[[bin]]
name = "uptime"
path = "src/bin/uptime.rs"

[[bin]]
name = "stamp"
path = "src/bin/stamp.rs"

[[bin]]
name = "probe"
path = "src/bin/probe.rs"

[[bin]]
name = "spare"
path = "src/bin/spare.rs"

[dependencies]
galexy-rt = { path = "../galexy-rt" }
galexy-abi = { path = "../../galexy-abi" }

[build-dependencies]
galexy-abi = { path = "../../galexy-abi" }
